components_manager:
    coro_pool:
        initial_size: 500
        max_size: 1000

    task_processors:
        main-task-processor:
            worker_threads: 4

    default_task_processor: main-task-processor

    components:
        logging:
            fs-task-processor: main-task-processor
            loggers:
                default:
                    file_path: '@stderr'
                    level: debug

        # Клиент gRPC
        unstable-service-client:
            endpoint: $server-endpoint # Подставляется из переменных
            
            # ЗАДАНИЕ: Настройте параметры QoS
            qos:
                attempts: 3         # Retry
                timeout-ms: 2000    # Timeout
            
            # ЗАДАНИЕ: Включите Congestion Control (Circuit Breaker аналог)
            congestion-control:
                enabled: true
